# Generated by Django 5.2.3 on 2025-07-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(max_length=20)),
                ('company_phone', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='company_logos/')),
            ],
        ),
    ]
