# Generated by Django 5.2.3 on 2025-07-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gst_number',
            field=models.CharField(max_length=50),
        ),
    ]
