# Generated by Django 5.2.3 on 2025-07-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('gst_number', models.CharField(max_length=20)),
                ('dealer_phone', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='dealer_logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
