# Generated by Django 5.2.3 on 2025-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dealer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='dealer_phone',
            new_name='company_phone',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='gst_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
