# Generated by Django 5.2.3 on 2025-07-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_dealer_phone_dealer_company_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
