# Generated by Django 5.2.3 on 2025-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_item_name_alter_item_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('gst', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
